config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  get 'home/about'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
    
  end
end

app/controllers/turbo_controller.rb
# class TurboController < ApplicationController
#     class Responder < ActionController::Responder
#       def to_turbo_stream
#         controller.render(options.merge(formats: :html))
#       rescue ActionView::MissingTemplate => error
#         if get?
#           raise error
#         elsif has_errors? && default_action
#           render rendering_options.merge(formats: :html, status: :unprocessable_entity)
#         else
#           redirect_to navigation_location
#         end
#       end
#     end
  
#     self.responder = Responder
#     respond_to :html, :turbo_stream
#   end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-container'>
  
  <div class='form-item'>
    <% form.label :first_name %>
    <%= form.text_field :first_name, placeholder: 'First Name' %>
  </div>

  <div class='form-item'>
    <% form.label :last_name %>
    <%= form.text_field :last_name, placeholder: 'Last Name' %>
  </div>

  <div class='form-item'>
    <% form.label :email %>
    <%= form.text_field :email, placeholder: 'Emails' %>
  </div>

  <div class='form-item'>
    <% form.label :phone %>
    <%= form.text_field :phone, placeholder:' Phone number' %>
  </div>

  <div class='form-item'>
    <% form.label :twitter %>
    <%= form.text_field :twitter, placeholder: 'Twitter' %>
  </div>

  <div>
    <%= form.submit class:'Button submit' %>
  </div>
  
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>" class='friend'>
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= friend.twitter %>
  </p>

</div>

app/views/friends/edit.html.erb
<h1 style='text-align: center'>Editing friend</h1>
<br>

<%= render "form", friend: @friend %>

<br>

<div class='show-btn'>
  <%= link_to "Show this friend", @friend, class: 'delete s-btn' %> |
  <%= link_to "Back to friends", friends_path, class: 'delete s-btn' %>
</div>

app/views/friends/index.html.erb
<h1 class='f-header'>Friends List</h1>

<div id="friends">
 <ul class=lists>
  <% @friends.each do |friend| %>
    <li>
    <%= render friend %>
    <p>
      <%= link_to "Show friend", friend %>
    </p>
    </li>
    
  <% end %>
 
 </ul>
<%= link_to "Add friend", new_friend_path, class:'Button' %>
</div>

app/views/friends/new.html.erb
<div class='form-render'>
<h1>New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path, class: 'Button' %>
</div>


</div>

app/views/friends/show.html.erb
<div class='show-jumbo'>

<%= render @friend %>

<div class='show-btn-container'>
  <div class='show-btn'>
  <%= link_to "Edit this friend", edit_friend_path(@friend), class: 'delete s-btn' %>
  <%= link_to "Back to friends", friends_path, class: 'delete s-btn' %>
  <%= button_to "Destroy this friend", @friend, method: :delete, class: 'delete'%>
  </div>
</div>

</div>

app/views/home/_footer.html.erb
<footer>
<p>Built with love by Ola.</p>
</footer>

app/views/home/_header.html.erb
<nav class='navigation'>
<%= link_to 'Home', root_path, class:'link'%>
<%= link_to 'Friends', friends_path, class:'link'%>
<%= link_to 'Add Friend', new_friend_path, class:'link'%>
<%= link_to 'About', home_about_path, class:'link'%>

<% if user_signed_in? %>
    <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:'link'%>
    <%= link_to 'Edit Profile', edit_user_registration_path, class:'link'%>
<% else %>

    <%= link_to 'Sign Up', new_user_registration_path, class:'link'%>
    <%= link_to 'Sign In', new_user_session_path, class:'link'%>
<% end %>


</nav>

app/views/home/about.html.erb
<h1>About Page</h1>

app/views/home/index.html.erb
<h1>Welcome home</h1>

app/views/layouts/_alerts.html.erb
  <p class="notice"><%= notice %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friends</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'home/header'%>
  <br>
    <div class='container'>

    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>
    <br>

      <%= yield %>
    </div>
    <%= render 'home/footer'%>
  </body>
</html>